# Generated by Django 6.0.3 on 2026-05-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Documento')),
                ('especialidad', models.CharField(choices=[('Alta Montaña', 'Alta Montaña'), ('Flora y Fauna', 'Flora y Fauna'), ('Cultura Local', 'Cultura Local'), ('Turismo de Aventura', 'Turismo de Aventura'), ('Avifauna', 'Avifauna'), ('Historia y Patrimonio', 'Historia y Patrimonio')], max_length=50, verbose_name='Especialidad')),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20, verbose_name='Disponibilidad')),
                ('experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('idiomas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Idiomas')),
                ('certificaciones', models.TextField(blank=True, null=True, verbose_name='Certificaciones')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('color_avatar', models.CharField(default='#2c6e3c', max_length=10, verbose_name='Color Avatar')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('paquete_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_del_paquete', to='reservas.paquete', verbose_name='Asignar Paquete Turístico')),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
