# Generated by Django 6.0.4 on 2026-04-30 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='paquete_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_del_paquete', to='reservas.paquete', verbose_name='Asignar Paquete Turístico'),
        ),
    ]
