# Generated by Django 6.0.3 on 2026-05-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_guia_paquete_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guia',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
