# Generated by Django 6.0.3 on 2026-04-20 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500)),
                ('estrellas', models.PositiveIntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='reservas.paquete')),
            ],
        ),
    ]
