# Generated by Django 6.0.4 on 2026-04-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500)),
                ('estrellas', models.PositiveIntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
