# Generated by Django 6.0.3 on 2026-04-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Documento')),
                ('especialidad', models.CharField(choices=[('Alta Montaña', 'Alta Montaña'), ('Flora y Fauna', 'Flora y Fauna'), ('Cultura Local', 'Cultura Local'), ('Turismo de Aventura', 'Turismo de Aventura'), ('Avifauna', 'Avifauna'), ('Historia y Patrimonio', 'Historia y Patrimonio')], max_length=50, verbose_name='Especialidad')),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20, verbose_name='Disponibilidad')),
                ('experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('idiomas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Idiomas')),
                ('certificaciones', models.TextField(blank=True, null=True, verbose_name='Certificaciones')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('color_avatar', models.CharField(default='#2c6e3c', max_length=10, verbose_name='Color Avatar')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Guía',
                'verbose_name_plural': 'Guías',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('cantidad_personas', models.PositiveIntegerField(default=1, verbose_name='Número de Personas')),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Pagado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Tour')),
                ('destino', models.CharField(default='Sogamoso, Boyacá', max_length=150, verbose_name='Lugar de Destino')),
                ('duracion_dias', models.PositiveIntegerField(default=1, verbose_name='Duración (Días)')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Base')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del recorrido')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
    ]
