# Generated by Django 6.0.4 on 2026-04-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Personas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del recorrido'),
        ),
        migrations.AddField(
            model_name='tour',
            name='destino',
            field=models.CharField(default='Sogamoso, Boyacá', max_length=150, verbose_name='Lugar de Destino'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=1, verbose_name='Duración (Días)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Pagado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_admin.tour'),
        ),
    ]
