# Generated by Django 6.0.4 on 2026-04-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Blog')),
                ('contenido', models.TextField(verbose_name='Contenido del Blog')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen Destacada')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('documento', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=20, verbose_name='Tipo de PQRS')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='pqrs/', verbose_name='Adjuntar Evidencia')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duración')),
                ('nivel_dificultad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, verbose_name='Nivel de Dificultad')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='reservas.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destinos/')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Total')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('actividades', models.ManyToManyField(related_name='paquetes', to='reservas.actividades', verbose_name='Actividades Incluidas')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Promoción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Oferta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/', verbose_name='Imagen del Banner')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace (URL)')),
                ('porcentaje_descuento', models.PositiveIntegerField(default=0, verbose_name='Porcentaje de Descuento (%)')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('prioridad', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Prioridad/Orden')),
                ('solo_usuarios', models.BooleanField(default=False, verbose_name='Solo usuarios registrados')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones', to='reservas.paquete', verbose_name='Paquete en Oferta')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('numero_personas', models.PositiveIntegerField(verbose_name='Número de Personas')),
                ('monto_total', models.IntegerField(editable=False, verbose_name='Monto Total')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.paquete', verbose_name='Paquete Reservado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
