# Generated by Django 6.0.4 on 2026-04-28 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monto Total'),
        ),
    ]
