# Generated by Django 6.0.4 on 2026-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('documento', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('Peticion', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=20, verbose_name='Tipo de PQRS')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='pqrs/', verbose_name='Adjuntar Evidencia')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
            },
        ),
    ]
