# Generated by Django 6.0.4 on 2026-04-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reserva_estado_remove_reserva_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='¿Está Activa?'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.IntegerField(editable=False, verbose_name='Monto Total'),
        ),
    ]
