# Generated by Django 6.0.4 on 2026-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_pqrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Blog')),
                ('contenido', models.TextField(verbose_name='Contenido del Blog')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen Destacada')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
