# Generated by Django 6.0.4 on 2026-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
