# Generated by Django 6.0.4 on 2026-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_categoria_estado_alter_reserva_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
    ]
