# Generated by Django 6.0.4 on 2026-04-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_paquete_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
    ]
