# Generated by Django 6.0.4 on 2026-04-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_blog_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='¿Está Activa?'),
        ),
    ]
